name: Enrich Reviews From Feefo

on:
  workflow_dispatch:  # ✅ Allows manual run from GitHub

jobs:
  run-enrichment:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Allows the workflow to commit files

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager openpyxl

      - name: Run enrich_with_reviews.py
        run: python enrich_with_reviews.py

      - name: Commit output to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull
          git add data/recent_reviews_web_ready.xlsx
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "Add enriched review report for $timestamp" || echo "No changes to commit"
          git push
