name: Weekly Feefo Report Agent

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    permissions:  # ⬅️ CRITICAL for push to work
      contents: write

    env:
      FEEFO_API_TOKEN: ${{ secrets.FEEFO_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI Agent
        run: python agent.py

      - name: Commit and push report to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/*.xlsx || echo "Nothing to add"
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "Add Feefo report for $timestamp" || echo "No changes to commit"
          git push
