name: Weekly Feefo Report Agent

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  workflow_dispatch:      # Also allows manual trigger

jobs:
  run-agent:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      FEEFO_API_TOKEN: ${{ secrets.FEEFO_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager openpyxl

      - name: Run Feefo API Agent
        run: python agent.py

      - name: Run Enrichment Scraper
        run: python enrich_with_reviews.py

      - name: Commit enriched reports
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull
          git add data/*.xlsx
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "Update Feefo and Review reports for $timestamp" || echo "No changes to commit"
          git push
