name: Weekly Feefo Report Agent

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  workflow_dispatch:      # Manual run option

jobs:
  run-agent:
    runs-on: ubuntu-latest

    env:
      FEEFO_API_TOKEN: ${{ secrets.FEEFO_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI Agent
        run: python agent.py

      - name: Upload report as artifact
uses: actions/upload-artifact@v3
with:
  name: feefo-report
  path: '**/feefo_product_ratings_week_*.xlsx'

